<a href="https://colab.research.google.com/github/2610geetha/Demofiles/blob/master/TensorflowDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np


In [ ]:
x= tf.Variable([list(range(15,20))]*5) # 2D tensor of shape (2,2)
y=tf.Variable([list(range(5, 10))]*5) # 2D tensor of shape (2,2)

print("x:", x)

print("y:", y)

x: <tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19]], dtype=int32)>
y: <tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]], dtype=int32)>


In [ ]:
z= x + y
print("z:", z) # element wise addition

w= x * y
print("w:", w)  # element wise multiplication

v= x/y
print("v:", v)  # element wise division, it supports inifinity and NaN

z: tf.Tensor(
[[20 22 24 26 28]
 [20 22 24 26 28]
 [20 22 24 26 28]
 [20 22 24 26 28]
 [20 22 24 26 28]], shape=(5, 5), dtype=int32)
w: tf.Tensor(
[[ 75  96 119 144 171]
 [ 75  96 119 144 171]
 [ 75  96 119 144 171]
 [ 75  96 119 144 171]
 [ 75  96 119 144 171]], shape=(5, 5), dtype=int32)
v: tf.Tensor(
[[3.         2.66666667 2.42857143 2.25       2.11111111]
 [3.         2.66666667 2.42857143 2.25       2.11111111]
 [3.         2.66666667 2.42857143 2.25       2.11111111]
 [3.         2.66666667 2.42857143 2.25       2.11111111]
 [3.         2.66666667 2.42857143 2.25       2.11111111]], shape=(5, 5), dtype=float64)


In [ ]:
print("addition:", tf.add(x,y))

addition: tf.Tensor(
[[20 22 24 26 28]
 [20 22 24 26 28]
 [20 22 24 26 28]
 [20 22 24 26 28]
 [20 22 24 26 28]], shape=(5, 5), dtype=int32)


In [ ]:
print("multiplication: ", tf.multiply(x,y))

multiplication:  tf.Tensor(
[[ 75  96 119 144 171]
 [ 75  96 119 144 171]
 [ 75  96 119 144 171]
 [ 75  96 119 144 171]
 [ 75  96 119 144 171]], shape=(5, 5), dtype=int32)


In [ ]:
print("division: ", tf.divide(x,y))

division:  tf.Tensor(
[[3.         2.66666667 2.42857143 2.25       2.11111111]
 [3.         2.66666667 2.42857143 2.25       2.11111111]
 [3.         2.66666667 2.42857143 2.25       2.11111111]
 [3.         2.66666667 2.42857143 2.25       2.11111111]
 [3.         2.66666667 2.42857143 2.25       2.11111111]], shape=(5, 5), dtype=float64)


In [ ]:
tensor1 = tf.random.uniform((2,2), minval= 1, maxval= 20, dtype= tf.int32)
print("Initial tensor: ", tensor1.numpy())
tensor2 = tf.pow(tensor1, 2)
print("Squared tensor = ", tensor2.numpy())

Initial tensor:  [[ 9  1]
 [ 8 13]]
Squared tensor =  [[ 81   1]
 [ 64 169]]


In [ ]:
tensor1 = tf.random.uniform((2,2), minval= 1, maxval= 20)
print("Initial tensor: ", tensor1.numpy())
tensor2 = tf.pow(tensor1, 2)
print("Squared tensor = ", tensor2.numpy())

Initial tensor:  [[ 8.623651 16.721968]
 [11.641601 18.309574]]
Squared tensor =  [[ 74.36735 279.6242 ]
 [135.52687 335.2405 ]]


In [ ]:
tensor1 = tf.random.uniform((2,2), minval= 1, maxval= 20, dtype= tf.int32)
print("Initial tensor: ", tensor1.numpy())
tensor2 = tensor1 * tensor1
print("Squared tensor = ", tensor2.numpy())

Initial tensor:  [[13 17]
 [10  8]]
Squared tensor =  [[169 289]
 [100  64]]


In [ ]:

tensor1 = tf.random.uniform((2,2), minval= 1, maxval= 20, dtype= tf.int32)
print("Initial tensor: ", tensor1.numpy())
tensor2 = tf.multiply( tensor1 , tensor1)
print("Squared tensor = ", tensor2.numpy())

Initial tensor:  [[ 5 15]
 [ 5  4]]
Squared tensor =  [[ 25 225]
 [ 25  16]]


In [ ]:
t1 = tf.Variable([[2,3,4], [5,7,9], [1,6,3], [5,8,4]])
t2 = tf.Variable([[2,3,4,5], [5,7,9,4], [1,6,3,9]])

t3 = t1 + t2

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [4,3] vs. [3,4] [Op:AddV2] name: 

In [ ]:
var1 = tf.Variable([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]])
var2 = tf.Variable([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])
op1 = tf.linalg.matmul(var1,var2)
print("matrix maultiplication :", op1)

matrix maultiplication : tf.Tensor(
[[ 90 100 110]
 [240 275 310]
 [390 450 510]
 [540 625 710]
 [690 800 910]], shape=(5, 3), dtype=int32)


In [ ]:
#Matrix inverse
try:
  x = tf.Variable([[2,3],[3,3]])
  xinv = tf.linalg.inv(x)
  print("inverse of x:", xinv)
except Exception as e:
  print("exception occured:", str(e))

exception occured: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse] name: 


In [ ]:
x=tf.cast(x,tf.float32)
xinv = tf.linalg.inv(x)
print("inverse of x:", xinv)

inverse of x: tf.Tensor(
[[-1.         1.       ]
 [ 1.        -0.6666667]], shape=(2, 2), dtype=float32)


In [ ]:
coeff = tf.Variable([[1,1,1,1],[2,3,0,-1],[-3,4,1,2],[1,2,-1,1]],dtype=tf.float32)
coeff

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 1.,  1.,  1.,  1.],
       [ 2.,  3.,  0., -1.],
       [-3.,  4.,  1.,  2.],
       [ 1.,  2., -1.,  1.]], dtype=float32)>

In [ ]:
y = tf.Variable([[13],[-1],[10],[1]],dtype=tf.float32)
y

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[13.],
       [-1.],
       [10.],
       [ 1.]], dtype=float32)>

In [ ]:
inv_coeff = tf.linalg.inv(coeff)
inv_coeff

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 2.77777791e-01,  5.55555224e-02, -1.66666672e-01,
         1.11111104e-01],
       [-7.40740746e-02,  1.85185164e-01,  1.11111104e-01,
         3.70370336e-02],
       [ 4.62962925e-01,  9.25926119e-02,  5.55555634e-02,
        -4.81481493e-01],
       [ 3.33333343e-01, -3.33333343e-01, -9.93410776e-09,
         3.33333343e-01]], dtype=float32)>

In [ ]:
print("solution : ", tf.matmul(inv_coeff,y))

solution :  tf.Tensor(
[[ 2.0000000e+00]
 [-1.0058284e-07]
 [ 5.9999995e+00]
 [ 5.0000005e+00]], shape=(4, 1), dtype=float32)


In [ ]:
w=tf.Variable([[0.5,1,-1.2]],dtype=tf.float32)
#w=tf.Variable([[0.5,1]],dtype=tf.float32)
print("w: ",w)

x = tf.Variable([[0.2],[1],[0.5]])
print("x: ",x)

b= tf.Variable([0.01])
print("b: ",b)



w:  <tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[ 0.5,  1. , -1.2]], dtype=float32)>
x:  <tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.2],
       [1. ],
       [0.5]], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.01], dtype=float32)>


In [ ]:
try:
  y= tf.linalg.matmul(w,x)
  print("y:", y)
except Exception as e:
  print("exception occured", str(e))


y: tf.Tensor([[0.5]], shape=(1, 1), dtype=float32)


In [ ]:
print("Solution :", tf.sigmoid(tf.add(y,b)))

Solution : tf.Tensor([[0.62480646]], shape=(1, 1), dtype=float32)


In [ ]:
x = tf.Variable([[0.2, 1, 0.5]])

w = tf.Variable([[0.5], [1] , [-1.2]])

b = tf.Variable([[0.01]])



a = tf.add(tf.matmul(x,w), b)



p = tf.sigmoid(a)

print(p.numpy()[0][0])

0.62480646
